application: comp3207k
version: 1
runtime: python27
api_version: 1
threadsafe: true




handlers:

- url: /bootstrap
  static_dir: templates/bootstrap

- url: /images
  static_dir: templates/images

- url: /.*
  script: controllers.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

